name: echo
on:
  workflow_dispatch:
    inputs:
      config-path:
        required: true
        description: 'Path to the config file'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo ${{ inputs.config-path }}


