name: echo
on:
  workflow_dispatch:
    inputs:
      config-path:
        required: true
        description: 'Path to the config file'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        id: create-tag
        uses: jaywcjlove/create-tag-action@main
        with:
          test: '^release:'

      - run: echo "yes"
        if: steps.create-tag.outputs.successful == 'true'

      - run: echo "no"
        if: steps.create-tag.outputs.successful == 'false'
