name: echo
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo ${{ inputs.config-path }}


