name: tag
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
