name: c tag
run-name: "创建tag: (${{ github.event.head_commit.message }})"
on:
  create:
  workflow_dispatch:

jobs:
  release-gitee:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: t1
        run: |
            echo "---触发了tag创建事件---"