name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          path: 'current'

      - name: Upload config before build
        uses: actions/upload-artifact@v4
        with:
          name: config before build
          path: current/README.md
