name: on push
run-name: "推送时固定执行: (${{ github.event.head_commit.message }})"
on:
  push:
  workflow_dispatch:

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: t1
        run: |
          echo "---test end---"

      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
            for (const id in github.rest.git) {
              console.log(id)
            }