name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create/Update tag
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: v1.0.0
          tag_exists_error: false
      - run: zip -r hub.zip .github

      - name: 上传编译结果到 Artifact (Upload build result to Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: hub
          path: hub.zip

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: 'hub.zip'
          tag: v1.0.0
