name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: create tag
        uses: jaywcjlove/create-tag-action@v2.1.0
        with:
          version: v1.0.0

      - run: zip -r hub.zip .github

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: 'hub.zip'
          tag: v1.0.0

#重复
