name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dusansimic/trigger-workflow-action@v0.1.0
        with:
          name: echo.yml
          owner: bling-yshs
          repo: action-test
