name: test
on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'OpenWrt 仓库的拥有者'
        type: string
        required: true
      repo:
        description: 'OpenWrt 仓库的名字'
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{inputs.owner}}
