name: on push
run-name: "推送时固定执行: (${{ github.event.head_commit.message }})"
on:
  push:
  workflow_dispatch:

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: t1
        run: |
          echo "---test end---"

      - name: Create a tag on prisma-engines repository
        uses: actions/github-script@v6
        id: tag-prisma-engines
        env:
          REPO_NAME: 'acition-test'
          TAG_NAME: 'v0.0.1'
          MESSAGE: 'no message'
        with:
          result-encoding: string
          script: |
            const commitNewTag = await github.rest.git.createTag({
              owner: 'bling-yshs',
              repo: '${{ env.REPO_NAME }}',
              tag: '${{ env.TAG_NAME }}',
              message: '${{ env.MESSAGE }}',
              object: context.payload.commits.id,
              type: 'commit',
            })

            await github.rest.git.createRef({
              owner: 'prisma',
              repo: '${{ env.REPO_NAME }}',
              ref: `refs/tags/${{ env.TAG_NAME }}`,
              sha: commitNewTag.data.sha,
            })