name: update
run-name: '更新启动器公告'
on:
  workflow_dispatch:

jobs:
  sync-to-gitee:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: Mirror GitHub to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/bling-yshs
          dst: gitee/bling_yshs
          force_update: true
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_PERSIONAL_TOKEN }}
          mappings: "new-empty=>new-empty-test"
          static_list: "new-empty"
