name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV
      - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')"

      - run: echo ${{env.previous_tag}}
