name: test
run-name: 这是一个自定义的名字
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo hello
# 这是一次提交
# 这是第二次提交
