name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          test: '^release:'

      - run: echo ${{ steps.create_tag.outputs.successful }}

      - run: echo "yes"
        if: steps.create_tag.outputs.successful == 'true'

      - run: echo "no"
        if: steps.create_tag.outputs.successful == 'false'
