name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'bling-yshs/HYZL-updater'
          path: 'updater'

      - run: |
          ls -al
          pwd
          

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'padavanonly/immortalwrtARM'
          path: 'test'

      - run: |
          ls -al
          pwd
