name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "previous_tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
      - run: echo "previous_tag=$(git describe --tags `git rev-list --tags --max-count=1`)"

      - run: echo ${{env.previous_tag}}
