name: on push
run-name: "推送时固定执行: (${{ github.event.head_commit.message }})"
on:
  push:
  workflow_dispatch:

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: t1
        run: |
          echo "---test end---"

      - name: Create a tag on prisma-engines repository
        uses: actions/github-script@v6
        id: tag-prisma-engines
        env:
          TAG_NAME: 'v0.0.2'
        with:
          result-encoding: string
          script: |
            for (const id in context) {
              console.log(id)
              console.log('-----------------------ddd----------------------')
            }
            const commitNewTag = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.payload.repository.name,
              tag: '${{ env.TAG_NAME }}',
              message: context.payload.commits[0].message,
              object: context.payload.commits[0].id,
              type: 'commit',
            })

            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.payload.repository.name,
              ref: `refs/tags/${{ env.TAG_NAME }}`,
              sha: commitNewTag.data.sha,
            })