name: test
run-name: 这是一个自定义的名字
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'bling-yshs/HYZL-updater'

      - run: |
          ls -al
          apt update
          apt-get install tree
          tree
