name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print GitHub context
        run: echo "${{ toJSON(github) }}"

      - name: Print Job context
        run: echo "${{ toJSON(job) }}"

      - name: Print Steps context
        run: echo "${{ toJSON(steps) }}"

      - name: Print Runner context
        run: echo "${{ toJSON(runner) }}"
