name: test
on:
  workflow_dispatch:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4
        with:
          path: 'current'

      - run: echo ok
