name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Invoke workflow with inputs
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: echo.yml
          inputs: '{ "config-path": "你好" }'

